CREATE TABLE `USER_ACCOUNT` (
 `USER_ID` varchar(20) NOT NULL COMMENT '사용자_아이디',
 `USER_PW` varchar(20) NOT NULL COMMENT '사용자_패스워드',
 `USER_NM` varchar(20) NOT NULL COMMENT '사용자_이름',
 `USER_LEVEL` varchar(20) NOT NULL DEFAULT 100 COMMENT '사용자_레벨',
 `COMPANY_CD` varchar(20) NOT NULL DEFAULT 'charves' COMMENT '업체_코드',
 `DESCRIPTION` varchar(200) COMMENT '설명',
 PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자_계정';

CREATE TABLE `COMPANY_INFO` (
 `COMPANY_ID` varchar(20) NOT NULL COMMENT '기업_아이디',
 `COMPANY_NM` varchar(50) NOT NULL COMMENT '기업_이름',
 `MANAGER_NM` varchar(50) NOT NULL COMMENT '담당자_이름',
 `MANAGER_TEL` varchar(20) NOT NULL COMMENT '담당자_전화',
 `ADDRESS` varchar(300) DEFAULT null COMMENT '주소',
 `LATITUDE` double(11.8) DEFAULT null COMMENT '위도',
 `LONGITUDE` double(11.8) DEFAULT null COMMENT '경도',
 PRIMARY KEY (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='기업_정보';

CREATE TABLE `PRODUCT_MASTER` (
 `PRODUCT_ID`  varchar(20) NOT NULL COMMENT '제품_아이디',
 `PRODUCT_NM`  varchar(100) NOT NULL COMMENT '제품_이름',
 `WEIGHT` double NOT NULL DEFAULT 0 COMMENT '무게',
 `SIZE_H` double NOT NULL DEFAULT 0 COMMENT '가로크기',
 `SIZE_V` double NOT NULL DEFAULT 0 COMMENT '세로크기',
 `SIZE_Z` double NOT NULL DEFAULT 0 COMMENT '높이',
 `PRICE` int(10) NOT NULL DEFAULT 0 COMMENT '가격',
 PRIMARY KEY (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='제품_마스터';

CREATE TABLE `GOODS` (
 `PRODUCT_ID` varchar(20) NOT NULL COMMENT '제품_아이디',
 `SERIAL_NO` varchar(20) NOT NULL COMMENT '일련_번호',
 `MANUFACTURING_DTTM` varchar(14) NOT NULL DEFAULT DATE_FORMAT(CURRENT_TIMESTAMP(), '%Y%m%d%H%i%s') COMMENT '지제_일시',
 `LOT_NO` varchar(4) DEFAULT null COMMENT '제조_라인번호',
 PRIMARY KEY (`PRODUCT_ID`,`SERIAL_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='상품';

CREATE TABLE `ORDER_MASTER` (
 `ORDER_NO` varchar(30) NOT NULL COMMENT '주문_번호',
 `ORDER_DTTM` varchar(14) NOT NULL DEFAULT DATE_FORMAT(CURRENT_TIMESTAMP(), '%Y%m%d%H%i%s') COMMENT '주문_일시',
 `COMPANY_ID` varchar(20) NOT NULL COMMENT '기업_아이디',
 `CUSTOM_ID` varchar(20) NOT NULL COMMENT '고객_아이디',
 `TOTAL_PRICE` int(10) NOT NULL COMMENT '총_가격',
 `PURCHASE` int(10) NOT NULL COMMENT '지불금액',
 `BILL_NO` varchar(20) COMMENT '선적_번호',
 `BILL_DTTM` varchar(14) COMMENT '선적_일시',
 `DLV_ADDR` varchar(300) NOT NULL COMMENT '배송_주소',
 `ARRIVE_YN` varchar(1) DEFAULT 'N' COMMENT '도착여부',
 PRIMARY KEY (`ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='주문_마스터';

CREATE TABLE `ORDER_GOOD` (
 `ORDER_NO` varchar(30) NOT NULL COMMENT '주문_번호',
 `PRODUCT_ID` varchar(20) NOT NULL COMMENT '제품_아이디',
 `COUNT` int(10) NOT NULL DEFAULT 0 COMMENT '개수',
 PRIMARY KEY (`ORDER_NO`,`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='주문_상품';

CREATE TABLE `ORDER_OUT_GOOD` (
 `PRODUCT_ID` varchar(20) NOT NULL COMMENT '제품_아이디',
 `SERIAL_NO` varchar(20) NOT NULL COMMENT '일련_번호',
 `OUT_TYPE` varchar(10) COMMENT '출고_구분',
 `ORDER_NO` varchar(30) DEFAULT null COMMENT '주문_번호',
 PRIMARY KEY (`PRODUCT_ID`,`SERIAL_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='주문_출고_상품';

CREATE TABLE `COMM_CODE_GROUP` (
 `GROUP_ID` varchar(10) NOT NULL COMMENT '그룹_아이디',
 `GROUP_NM` varchar(50) NOT NULL COMMENT '그룹_이름',
 `USE_YN` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용_여부',
 `DESCRIPTION` varchar(300) COMMENT '설명',
 `REG_DTTM` varchar(14) NOT NULL DEFAULT DATE_FORMAT(CURRENT_TIMESTAMP(), '%Y%m%d%H%i%s') COMMENT '등록_일시',
 PRIMARY KEY (`GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='공통_코드_그룹';

CREATE TABLE `COMM_CODE` (
 `GROUP_ID` varchar(10) NOT NULL COMMENT '그룹_아이디',
 `CODE_ID` varchar(10) NOT NULL COMMENT '코드_아이디',
 `CODE_NM` varchar(50) NOT NULL COMMENT '코드_이름',
 `USE_YN` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용_여부',
 `DESCRIPTION` varchar(200) COMMENT '설명',
 `REG_DTTM` varchar(14) NOT NULL DEFAULT DATE_FORMAT(CURRENT_TIMESTAMP(), '%Y%m%d%H%i%s') COMMENT '등록_일시',
 PRIMARY KEY (`GROUP_ID`,`CODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='공통_코드';

